# Generated by Django 4.2 on 2024-11-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='genre',
        ),
    ]
