# Generated by Django 4.2 on 2024-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_category_genre_rename_category_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content',
            field=models.TextField(default='داستانی عالی'),
        ),
    ]
