# Generated by Django 4.2 on 2024-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='attributes',
            new_name='section',
        ),
    ]
